### PR TITLE
Add babel build script to allow for layer2 inclusion in minified browser app

### PR DESCRIPTION
**Pull request by alexanvl**

### CODE REVIEW

**Comment by jadbox** [comment]
@alexanvl looking good, add an `npm start` package.json script that puts webpack into hot build mode so that it recompiles upon changes. This helps for general development workflow.

**Comment by jadbox** [comment]
also it'll be a good idea to add Source Maps by default as at this stage we should assume a few extra bytes is worth it for improving debugging support

**Comment by alexanvl** [comment]
@jadbox So I don't think it makes sense to have webpack as a module level dependency.  The module is intended to be used within both a node app and a browser app, so all that's missing is the built distribution for browser so it can be included and webpacked on that end.

**Comment by alexanvl** [comment]
No urgency to merge either, if you'd like to wait until full webpack support can be added I think that's fine and I'll change the PR to WIP

**Comment by nginnever** [comment]
awesome job, thank you!

**Pull request merged**
